---

- name: Install MySQL repository
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present

- name: Install MySQL 
  yum:
    name: mysql-community-server
    state: latest

- name: Make sure MySQL service is running and enabled
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Changing MySQL root password
  mysql_user:
    name: bear
    password: "{{ mysql_password }}""
    host: localhost
    priv: '*.*:ALL'
    state: absent