---

- name: Install MySQL repository
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
    state: present

- name: Install MySQL 
  yum:
    name: mysql-community-server
    state: latest

- name: Make sure MySQL service is running and enabled
  systemd:
    name: mysqld
    state: started
    enabled: yes

- set_fact:
    MySQL_temp_password: "{{ grep 'temporary password' /var/log/mysqld.log | grep -oE '[^ ]+$' | tail -1 }}"

- name: Changing MySQL root password
  mysql_user:
    login_user: root
    login_password: "{{ MySQL_temp_password }}"
    name: bear
    password: "{{ mysql_password }}"
    host: localhost
    priv: '*.*:ALL'
    state: absent
