#--------------------------------------------------------------------
#--General Setup
#--------------------------------------------------------------------
caddy: true # Only caddy supported atm
installation_directory: /var/bearicade
#--------------------------------------------------------------------
#--HTTP(s) Setup
#--------------------------------------------------------------------
http_port: 80
https_enabled: true
https_port: 443
#--------------------------------------------------------------------
#--MySQL Setup
#--------------------------------------------------------------------
mysql_port: 5190
mysql_password: Password@123
#--------------------------------------------------------------------
#--Caddy Server Setup
#--------------------------------------------------------------------

