#--------------------------------------------------------------------
#--General Setup
#--------------------------------------------------------------------
installation_directory: /var/bearicade
bearicade_git: git@github.com:TA3/bearicade.git
private_key_path: ~/.ssh/id_rsa
web_user: www-data
web_group: www-data
#--------------------------------------------------------------------
#--HTTP(s) Setup
#--------------------------------------------------------------------
http_port: 80
https_enabled: true
https_port: 443
#--------------------------------------------------------------------
#--MySQL Setup
#--------------------------------------------------------------------
mysql_password: Password@123
#--------------------------------------------------------------------
#--Bear Server Settings
#--------------------------------------------------------------------
tfa_name: TA3 HPC
browser_recorder_limit: 9
login_recorder_days_limit: 180