---

- name: Clone bearicade from Github (TA3/bearicade)
  git:
    repo: '{{ bearicade_git }}'
    dest: /tmp/bearicade
    accept_hostkey: yes
    key_file: '{{ private_key_path }}'

- name: Copy bearicade files
  synchronize:
    src: /tmp/bearicade/
    dest: "{{ installation_directory }}"

- name: Copy dashboard database
  template:
    src: ../files/config.j2
    dest: "{{ installation_directory }}/config.php"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0600

- name: Copy login database
  template:
    src: ../files/loginConfig.j2
    dest: "{{ installation_directory }}/login/loginConfig.php"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0600

- name: Import Admin SQL database templates
  mysql_db:
    state: import
    name: all
    target: /tmp/bearicade/db_import/admin.sql

- name: Import Authentication SQL database templates
  mysql_db:
    state: import
    name: all
    target: /tmp/bearicade/db_import/auth.sql

- name: Import Bearicade SQL database templates
  mysql_db:
    state: import
    name: all
    target: /tmp/bearicade/db_import/bearicade.sql