---

- name: Clone bearicade from Github (TA3/bearicade)
  git:
    repo: '{{ bearicade_git }}'
    dest: /tmp/bearicade
    accept_hostkey: yes
    key_file: '{{ private_key_path }}'

- name: Copy bearicade files
  synchronize:
    src: /tmp/bearicade/
    dest: "{{ installation_directory }}"

- name: Copy dashboard database
  template:
    src: ../files/config.j2
    dest: "{{ installation_directory }}/config.php"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0600

- name: Copy login database
  template:
    src: ../files/loginConfig.j2
    dest: "{{ installation_directory }}/login/loginConfig.php"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0600

- name: Create Admin database
  mysql_db:
    name: admin
    state: present

- name: Import Admin SQL database templates
  mysql_db:
    state: import
    name: admin
    target: /tmp/bearicade/db_import/admin.sql
    login_user: bear
    login_password: "{{ mysql_password }}"

- name: Create Authentication database
  mysql_db:
    name: auth
    state: present

- name: Import Authentication SQL database templates
  mysql_db:
    state: import
    name: all
    target: /tmp/bearicade/db_import/auth.sql
    login_user: bear
    login_password: "{{ mysql_password }}"

- name: Create Bearicade database
  mysql_db:
    name: bearicade
    state: present

- name: Import Bearicade SQL database templates
  mysql_db:
    state: import
    name: all
    target: /tmp/bearicade/db_import/bearicade.sql
    login_user: bear
    login_password: "{{ mysql_password }}"