---

- name: Install epel-release and yum-utils
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - epel-release
    - yum-utils

- name: Install PHP repository
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Enable PHP repository
  ini_file:
    path: /etc/yum.repos.d/remi-php72.repo
    section: remi-php72
    option: enabled
    value: 1

- name: Install PHP and essentials 
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd